name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test workflow
        run: echo "Workflow funcionando"